# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'


  # Pods for ReactNativeStarter

  target 'ReactNativeStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeStarter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeStarter-tvOS

  target 'ReactNativeStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
